### ISSUE TITLE
Numbers view table and top toolbar too wide

### ISSUE THREAD

**Issue by ayya-vimala** [BuddhaNexus/buddhanexus-frontend#128]
Go to any sutta in numbers view and see that the toolbar with the filters icon disappears to the right. Same with the table itself which is much too wide.

**Comment by TrebuhD** [comment]
@ayya-vimala I wasn't able to reproduce this, but please check if it's fixed in the `static-pages` branch if you can.

**Comment by ayya-vimala** [comment]
No, it's not fixed. Open the left side-menu and then the whole lot moves to the right out of the viewport.

**Comment by ayya-vimala** [comment]
![image](https://user-images.githubusercontent.com/49606945/77831369-00db6000-712f-11ea-9eb0-ff7710477cce.png)
